---
title: "Week 4 Task"
author: "Matthew Lam"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data
```{r}
deathsraw <- read.csv("deathsdata_raw.csv")
deathsraw
```


# Cleaning
```{r}
library(tidyverse)
library(lubridate)

#format the date column
deathsraw$submission_date <- as.Date(deathsraw$submission_date, "%d/%m/%y")


#make a column for month
deathsraw$month <- month(deathsraw$submission_date) 
unique(deathsraw$state)

#filter out non-states
deathsraw <- deathsraw %>% filter(state!="FSM",state!="NYC",state!="RMI", state!="GU", state!="MP", state!="PR", state!="VI", state!="PW", state!="AS", state!="DC")

#get states object
states <- unique(deaths_clean$state)

#get average for each month 
for(i in 1:12){
  for(j in states){
  month <- deathsraw %>% filter(month==i)
  state <- j
  average_death_month <- mean(month$new_death[month$state==j])
  
  deathsraw$month_average_death[deathsraw$month==i & deathsraw$state==j] <- average_death_month
  }
   
  
}

#make a new dataset
deaths_clean <- deathsraw %>% group_by(state, month) %>% summarise(month_average_death=mean(month_average_death)) 

deathsraw %>% group_by(state, month) %>% summarise(month_average_death=mean(new_death))


#check
length(unique(deaths_clean$state))


#now to wide form
library(tidyr)
deaths_clean <- spread(deaths_clean, month, month_average_death)
deaths_clean %>% select(state, 1:12)
# write to csv
write.csv(deaths_clean, "deaths_clean.csv")

deaths_clean
```



## New Cases
```{r}
library(tidyverse)
library(lubridate)


#get states object
states <- unique(deaths_clean$state)

#get average for each month 
for(i in 1:12){
  for(j in states){
  month <- deathsraw %>% filter(month==i)
  state <- j
  average_newcases_month <- mean(month$new_case[month$state==j])
  
  deathsraw$month_average_newcases[deathsraw$month==i & deathsraw$state==j] <- average_newcases_month
  }
   
  
}

#make a new dataset
deaths_clean <- deathsraw %>% group_by(state, month) %>% summarise(month_average_newcases=mean(month_average_newcases)) 



#check
length(unique(deaths_clean$state))


#now to wide form
library(tidyr)
newcases_clean <- spread(deaths_clean, month, month_average_newcases)
newcases_clean <- newcases_clean  %>% select(state, 1:13)
# write to csv
write.csv(newcases_clean , "newcases_clean.csv")

newcases_clean 
```




## Read in Vax Data
```{r}
#load data
vaxdata <- read.csv("vax_clean.csv")
vaxdata

#remove non-states
vaxdata <- vaxdata %>% filter(Location.State!="American Samoa", Location.State!= "Bureau of Prisons",Location.State!="Dept of Defense", Location.State!="District of Columbia", Location.State!="Federated States of Micronesia", Location.State!="Guam", Location.State!="Indian Health Svc", Location.State!="Marshall Islands", Location.State!="Northern Mariana Islands", Location.State!="Republic of Palau", Location.State!="Veterans Health", Location.State!="Virgin Islands", Location.State!="United States", Location.State!="Puerto Rico")

vaxdata %>% filter(Location.State=="New York State")
vaxdata[32,2] <- "New York"

#check 
length(unique(vaxdata$Location.State))

#get state abbreviations
library(rvest)
#scrape from this website
url <- "https://abbreviations.yourdictionary.com/articles/state-abbrev.html"
abbreviations <- url %>% 
  read_html() %>% 
  html_nodes(xpath='//table') %>% 
  html_table


#clean up table 
abbreviations <- as.data.frame(abbreviations[1])
#omit headder
abbreviations <- abbreviations[-1,1:2]
#cleanup colnames 
colnames(abbreviations) <- c("state", "abbreviation")

#check
length(unique(abbreviations$state))

#save
write.csv(abbreviations, "us_states_abbreviations.csv")
```



## join vax data with deaths data
```{r}
abbr_joined <-merge(vaxdata, abbreviations, by.x="Location.State", by.y="state")

vax_deaths_joined <- merge(deaths_clean, abbr_joined, by.x="state", by.y="abbreviation")

#check 
length(vax_deaths_joined$state)
```


# re clean vax data
```{r}
vax_raw <- read.csv("vaxdata_rawv2.csv")
vax_raw





vax_raw$total_vaccinations_per_hundred[1]+((vax_raw$total_vaccinations_per_hundred[3]-vax_raw$total_vaccinations_per_hundred[1])/2)

vax_raw$total_vaccinations_per_hundred[2+12+12]



#another method
#first format date
vax_raw$date  <- as.Date(vax_raw$date, '%d/%m/%y')
vax_raw$month <- month(vax_raw$date)

vax_raw[vax_raw$month==2,]

#imputation for feb
for (i in row.names(vax_raw[vax_raw$month==2,])){#need to fix this imputation doesn't work. 
 
   #missing row
  vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)] <-
    vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)-1]+
    ((vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)+2]-
        vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)-1])/2)
  
}


#imputation for the rest missing data
for (i in row.names(vax_raw[is.na(vax_raw$people_fully_vaccinated_per_hundred)==T,])){#need to fix this imputation doesn't work. 
 
   #missing row
  vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)] <-
    vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)-1]+
    ((vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)+2]-
        vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)-1])/2)
  
}


for (i in row.names(vax_raw[is.na(vax_raw$people_fully_vaccinated_per_hundred)==T,])){#need to fix this imputation doesn't work. 
 
   #missing row
  vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)] <-
    vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)-1]+
    ((vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)+4]-
        vax_raw$people_fully_vaccinated_per_hundred[as.numeric(i)-1])/2)
  
}


#no more
row.names(vax_raw[is.na(vax_raw$people_fully_vaccinated_per_hundred)==T,])


vax_raw <- vax_raw %>% select(date, location, people_fully_vaccinated_per_hundred)


#long to wide
vax_clean <- spread(vax_raw, date, people_fully_vaccinated_per_hundred)

colnames(vax_clean) <- c("location", "Jan_vax", "Feb_vax", "Mar_vax", "Apr_vax", "May_vax", "Jun_vax", "Jul_vax", "Aug_vax", "Sep_vax", "Oct_vax", "Nov_vax", "Dec_vax")


#filter out non states 
vax_clean <- vax_clean %>% filter(location!="United States")
vax_clean[32,1] <- "New York"

colnames(vax_clean)[1] <- "state"

#write to csv
write.csv(vax_clean, 'vax_clean.csv')
```



## rejoin again
```{r}
vax_deaths_joined <- vax_deaths_joined %>% select(state, 1:12, Location.State)
colnames(vax_deaths_joined) <- c("state", "Location.State", 1:12)
vax_deaths_joined <- merge(vax_deaths_joined, vax_clean, by.x="Location.State", by.y="location")
```





#mapping 
```{r}
library(usmap)
cols <- c("f3e0f7","e4c7f1","d1afe8","b998dd","9f82ce","826dba","63589f")

#find the ranges of the colours
for(i in 2:13){
  print(i)
  print(range(deaths_clean[,i]),  na.rm=T)
}


#deaths trial map
plot_usmap(data = deaths_clean, values = "2", color = "gray") + 
  # scale_fill_viridis_c(name="Average Monthly New Deaths", limits=c(0,120))+
  scale_fill_continuous(low="lightgoldenrodyellow", high="tomato4", limits=c(0,120), breaks=c(0,30,60,90,120))+
  theme(legend.position = "right")


#texas
deaths_clean %>% filter(state=="TX")


#now in a for loop - deaths
for(i in 1:12){
  assign(paste0("mapdeaths",i,sep=""),
         plot_usmap(data = deaths_clean, values = paste("X",i, sep=""), color = "gray") + 
           scale_fill_continuous(low="white", high="tomato4", limits=c(0,100), breaks=c(0,30,60,90,120))+
           theme(legend.position = "right"))
  
  ggsave(paste0("mapdeaths",i,".pdf",sep=""))

}


for(i in 1:12){
  print(range(vax_deaths_joined[,i]))
}



#for loop - vax
for(i in 1:12){
  assign(paste0("mapvax",i,sep=""),
         plot_usmap(data = vax_clean, values = paste0(month.abb[i],"_vax",sep=""), color = "gray") + 
           scale_fill_continuous(low="wheat", high="slateblue", limits=c(0,100), breaks=c(0,20,40,60,80,100))+
           theme(legend.position = "right"))
  
  ggsave(paste0("mapvax",i,".pdf",sep=""))

}


plot_usmap(data = vax_deaths_joined, values = "Aug_vax", color = "gray") + 
           scale_fill_continuous(low="#fef6b5", high="#f16d7a", limits=c(0,100), breaks=c(0,20,40,60,80,100))+
           theme(legend.position = "right")
mapvax



for(i in 2:13){
  print(range(newcases_clean[,i]))
}


#now in a for loop - newcases
for(i in 1:12){
  assign(paste0("mapnewcases",i,sep=""),
         plot_usmap(data = newcases_clean, values = paste(i), color = "gray") + 
           scale_fill_continuous(low="white", high="tomato4", limits=c(85,12000), breaks=c(100,5000,10000,15000))+
           theme(legend.position = "right"))
  
  ggsave(paste0("mapnewcases",i,".pdf",sep=""))

}
```





